# Generated by Django 5.1.6 on 2025-04-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomCli', models.CharField(max_length=16, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=30, unique=True, verbose_name='Correo Electrónico')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntos', models.PositiveIntegerField(verbose_name='Puntuación')),
                ('medallas', models.PositiveIntegerField(default=0, verbose_name='Número de Medallas')),
                ('fecha_medalla', models.DateField(blank=True, null=True, verbose_name='Fecha Última Medalla')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='Bd_Escatica.usuario')),
            ],
        ),
    ]
